// Configuración básica de la aplicación
const AppConfig = {
    // Base de conocimiento en español
    knowledgeBaseES: [
        {
            intent: "comprar",
            keywords: ["comprar", "comprar casa", "comprar departamento", "adquirir", "invertir", "quiero casa"],
            response: "¡Qué excelente decisión! 🏠 Comprar una propiedad es de las mejores inversiones que puedes hacer. Cuéntame más: ¿buscas para vivir o para invertir?",
            options: [
                { text: "Para vivir", action: "BUY_LIVE" },
                { text: "Para invertir", action: "BUY_INVEST" }
            ]
        },
        {
            intent: "vender",
            keywords: ["vender", "vendo", "venta", "vender mi"],
            response: "¡Perfecto! Te ayudo a vender tu propiedad al mejor precio. ¿Ya tienes una'idée del valor aproximado?",
            options: [
                { text: "Quiero que me ayuden a tasarla", action: "LEAD", primary: true }
            ]
        },
        {
            intent: "unir",
            keywords: ["unir", "unir puntos", "unamos", "juntar", "comprar juntos"],
            response: "¡_GENIAL! Unir créditos es una excelente estrategia. Puedo juntar tu crédito con el de tu pareja, familiares o incluso amigos para comprar algo más grande. ¿Con quién quieres unir?",
            options: [
                { text: "Con mi pareja", action: "VALUE_PROP_JUMP" },
                { text: "Con mis papás", action: "VALUE_PROP_JUMP" },
                { text: "Con un amigo/a", action: "VALUE_PROP_JUMP" }
            ]
        },
        {
            intent: "puntos",
            keywords: ["puntos", "puntos infonavit", "credito", "requisitos", "cuantos puntos"],
            response: "Los puntos Infonavit se generan por tus aportaciones al vivienda. El mínimo para crédito es 1080 puntos. ¿Ya sabes cuántos tienes?",
            options: [
                { text: "Sí, tengo mis puntos", action: "KNOW_POINTS" },
                { text: "No sé cuántos tengo", action: "VALUE_PROP_JUMP" }
            ]
        }
    ],
    // Base de conocimiento en inglés
    knowledgeBaseEN: [
        {
            intent: "comparar",
            keywords: ["buy", "purchase", "home", "property"],
            response: "Great decision! 🏠 Buying property is one of the best investments. Tell me more: for living or investing?",
            options: [
                { text: "For living", action: "BUY_LIVE" },
                { text: "To invest", action: "BUY_INVEST" }
            ]
        },
        {
            intent: "vender",
            keywords: ["sell", "selling", "sale"],
            response: "Perfect! I'll help you sell your property at the best price.",
            options: [
                { text: "Help me value it", action: "LEAD", primary: true }
            ]
        },
        {
            intent: "unir",
            keywords: ["combine", "unite", "together", "joint"],
            response: "Excellent! Combining credits is a great strategy. We can join yours with your partner, family or friends.",
            options: [
                { text: "With my partner", action: "VALUE_PROP_JUMP" },
                { text: "With my parents", action: "VALUE_PROP_JUMP" }
            ]
        },
        {
            intent: "puntos",
            keywords: ["points", "credit", "requirements"],
            response: "Infonavit points are generated by your housing contributions. The minimum is 1080 points. Do you know yours?",
            options: [
                { text: "Yes, I know my points", action: "KNOW_POINTS" },
                { text: "I don't know", action: "VALUE_PROP_JUMP" }
            ]
        }
    ],
    // Traducciones
    translations: {
        es: {
            langBtn: "🇺🇸 EN",
            urgency: "🔥 <strong>Oportunidad:</strong> Mensualidades bajas y asesoría gratuita.",
            ctaNav: "Hablar con un Experto",
            heroBadge: "🌴 Especialistas en Cancún",
            heroTitle: "Tu hogar ideal, <br><span class='highlight'>sin estrés ni complicaciones</span>",
            heroSubtitle: "Descubre cómo aprovechar tus puntos Infonavit o expeditar tu venta.",
            trustTitle: "Expertos en todo México",
            mythsTitle: "Destruyendo Mitos del Infonavit 🔨",
            whyTitle: "¿Por qué elegirnos?",
            propTitle: "Desarrollos Destacados",
            testTitle: "Lo que dicen nuestros clientes",
            faqTitle: "Preguntas Frecuentes",
            chatHeaderName: "Juan, Tu Amigo Experto",
            chatHeaderRole: "Asesor Senior en Línea",
            chatInputPlaceholder: "Escribe tu mensaje...",
            chatTyping: "Escribiendo",
            pmCTA: "Quiero más información"
        },
        en: {
            langBtn: "🇲🇽 ES",
            urgency: "🔥 <strong>Opportunity:</strong> Low monthly payments and free advice.",
            ctaNav: "Talk to an Expert",
            heroBadge: "🏝️ Specialists in Cancun",
            heroTitle: "Your ideal home, <br><span class='highlight'>without stress or complications</span>",
            heroSubtitle: "Discover how to use your Infonavit points or speed up your sale.",
            trustTitle: "Experts across Mexico",
            mythsTitle: "Breaking Infonavit Myths 🔨",
            whyTitle: "Why Choose Us?",
            propTitle: "Featured Developments",
            testTitle: "What our clients say",
            faqTitle: "Frequently Asked Questions",
            chatHeaderName: "Juan, Your Expert Friend",
            chatHeaderRole: "Senior Agent Online",
            chatInputPlaceholder: "Type your message...",
            chatTyping: "Typing",
            pmCTA: "I want more information"
        }
    },
    // Datos de propiedades
    propertyDataBilingual: {
        es: {
            "prop1": {
                title: "Costa Azul Residence",
                badge: "Nuevo",
                price: "$1,450,000",
                desc: "Hermoso departamento frente al mar en zona hotelera de Cancún. 2 recámaras, 2 baños, cocina integral, amenidades de lujo.",
                propType: "Departamento",
                beds: 2,
                baths: 2,
                sqm: 95,
                location: "cancun",
                amenity: "Alberca, Gym, Seguridad 24h, Playa privada",
                images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800"],
                delivery: "Entrega Inmediata"
            },
            "prop2": {
                title: "Villas Tulum",
                badge: "Preventa",
                price: "$1,850,000",
                desc: "Villas independientes en Tulum centro. 3 recámaras, 3 baños, patio privado, cerca de la playa.",
                propType: "Casa",
                beds: 3,
                baths: 3,
                sqm: 150,
                location: "tulum",
                amenity: "Alberca, Jardín, Estacionamiento, Roof garden",
                images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800"],
                delivery: "Preventa"
            },
            "prop3": {
                title: "Plaza Las Américas",
                badge: "Entrega Inmediata",
                price: "$980,000",
                desc: "Departamento en Mérida norte, cerca de plazas comerciales. 1 recámara, 1 baño, buena distribución.",
                propType: "Departamento",
                beds: 1,
                baths: 1,
                sqm: 65,
                location: "merida",
                amenity: "Seguridad, Área común, Estacionamiento",
                images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
                delivery: "Entrega Inmediata"
            }
        },
        en: {
            "prop1": {
                title: "Costa Azul Residence",
                badge: "New",
                price: "$1,450,000",
                desc: "Beautiful beachfront apartment in Cancun hotel zone. 2 bedrooms, 2 bathrooms, kitchen, luxury amenities.",
                propType: "Apartment",
                beds: 2,
                baths: 2,
                sqm: 95,
                location: "cancun",
                amenity: "Pool, Gym, 24h Security, Private Beach",
                images: ["https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800"],
                delivery: "Immediate Delivery"
            },
            "prop2": {
                title: "Villas Tulum",
                badge: "Presale",
                price: "$1,850,000",
                desc: "Independent villas in Tulum center. 3 bedrooms, 3 bathrooms, private yard, near the beach.",
                propType: "House",
                beds: 3,
                baths: 3,
                sqm: 150,
                location: "tulum",
                amenity: "Pool, Garden, Parking, Roof garden",
                images: ["https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800"],
                delivery: "Presale"
            },
            "prop3": {
                title: "Plaza Las Américas",
                badge: "Immediate Delivery",
                price: "$980,000",
                desc: "Apartment in north Mérida, near shopping centers. 1 bedroom, 1 bathroom, good layout.",
                propType: "Apartment",
                beds: 1,
                baths: 1,
                sqm: 65,
                location: "merida",
                amenity: "Security, Common Area, Parking",
                images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
                delivery: "Immediate Delivery"
            }
        }
    }
};